window.ICOM_INBOX_RECORDS = [
  {
    "id": "inbox-2026-10-1029-2025ef006915",
    "inboxSourceId": "turn2search31",
    "title": "Mapping Philadelphia\u2019s Floodscape: A 35-Year Analysis of Coastal Urban Flood Drivers",
    "year": 2026,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Ning Sun",
    "venue": "Earth's Future",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "2026-01-18",
    "onlineFirst": "",
    "published": "2026-02-11",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1029/2025ef006915",
    "url": "https://doi.org/10.1029/2025ef006915",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search31"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: icom new paper. Shared by: Sun, Ning. SourceRefID: turn2search31.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed; Crossref match; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search31",
    "authors": [
      "Ning Sun",
      "Youngjun Son",
      "Cade Reesman",
      "Xue Li",
      "Mithun Deb",
      "William Perkins",
      "Zhaoqing Yang",
      "Karthik Balaguru",
      "David Judi"
    ],
    "pdfUrl": "https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2025EF006915",
    "crossrefUrl": "https://doi.org/10.1029/2025ef006915",
    "verifiedBy": "Melinda Muro",
    "authorAudit": "Verified",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  },
  {
    "id": "inbox-2026-10-1029-2025ef007162",
    "inboxSourceId": "turn2search31",
    "title": "Recent Tropical Cyclone Outer Size Increases in the Western North Atlantic",
    "year": 2026,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Karthik Balaguru",
    "venue": "Earth's Future",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "2025-11-21",
    "onlineFirst": "",
    "published": "2026-02-10",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1029/2025ef007162",
    "url": "https://doi.org/10.1029/2025ef007162",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search31"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: icom new paper. Shared by: Sun, Ning. SourceRefID: turn2search31.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed; Crossref match; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search31",
    "authors": [
      "Karthik Balaguru",
      "Chuan\u2010Chieh Chang",
      "L. Ruby Leung",
      "Paul A. Ullrich",
      "Yushan Han",
      "Julian R. Rice",
      "Samson Hagos",
      "Daniel Chavas",
      "Sourav Taraphdar",
      "Bryce Harrop",
      "Ning Sun",
      "David R. Judi"
    ],
    "pdfUrl": "https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2025EF007162",
    "crossrefUrl": "https://doi.org/10.1029/2025ef007162",
    "verifiedBy": "Melinda Muro",
    "authorAudit": "Verified",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  },
  {
    "id": "inbox-2025-10-1038-s41597-025-06186-z",
    "inboxSourceId": "turn2search31",
    "title": "Future North Atlantic tropical cyclone intensities in modified historical environments",
    "year": 2025,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Nicholas Lalo",
    "venue": "Scientific Data",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "",
    "onlineFirst": "",
    "published": "2025-12-05",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1038/s41597-025-06186-z",
    "url": "https://doi.org/10.1038/s41597-025-06186-z",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search31"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: icom new paper. Shared by: Sun, Ning. SourceRefID: turn2search31.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed; Crossref match; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search31",
    "authors": [
      "Nicholas Lalo",
      "Wenwei Xu",
      "Lili Yao",
      "Ning Sun",
      "Karthik Balaguru",
      "Julian Rice",
      "Serena Lipari",
      "Travis Thurber",
      "Zhaoqing Yang",
      "Mithun Deb",
      "David Judi"
    ],
    "pdfUrl": "https://www.nature.com/articles/s41597-025-06186-z.pdf",
    "crossrefUrl": "https://doi.org/10.1038/s41597-025-06186-z",
    "verifiedBy": "Melinda Muro",
    "authorAudit": "Verified",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  },
  {
    "id": "inbox-2025-unsafe-an-uncertain-structure-and-fragility-ensemble-framework-for-prope",
    "inboxSourceId": "turn2search31",
    "title": "UNSAFE: An UNcertain Structure And Fragility Ensemble framework for property-level flood risk estimation",
    "year": 2025,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Adam Pollack",
    "venue": "Journal of Open Source Software",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "",
    "onlineFirst": "",
    "published": "2025-11-13",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.21105/joss.07527",
    "url": "https://doi.org/10.21105/joss.07527",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search31"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: icom new paper. Shared by: Sun, Ning. SourceRefID: turn2search31. | Corrected lead author from inbox sharer to publisher metadata; DOI and author list verified from Crossref on 2026-06-10.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed | Crossref match; publisher DOI and PDF verified; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search31",
    "authors": [
      "Adam Pollack",
      "James Doss-Gollin",
      "Vivek Srikrishnan",
      "Klaus Keller"
    ],
    "pdfUrl": "https://joss.theoj.org/papers/10.21105/joss.07527.pdf",
    "authorAudit": "Verified",
    "crossrefUrl": "https://doi.org/10.21105/joss.07527",
    "verifiedBy": "Melinda Muro",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  },
  {
    "id": "inbox-2025-10-1016-j-ijdrr-2025-105825",
    "inboxSourceId": "turn2search35",
    "title": "Multi-decade analysis of flood risks to community infrastructure in Philadelphia",
    "year": 2025,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Youngjun Son",
    "venue": "International Journal of Disaster Risk Reduction",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "",
    "onlineFirst": "",
    "published": "2025-11-01",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1016/j.ijdrr.2025.105825",
    "url": "https://doi.org/10.1016/j.ijdrr.2025.105825",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search35"
    ],
    "action": "Ready for reporting; ScienceDirect PDF link may require institutional or publisher access.",
    "notes": "Source email subject: FW: PNNL ICoM Highlight: Multi-decade analysis of flood risks to infrastructure in Philadelphia. Shared by: Sun, Ning. SourceRefID: turn2search35.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed; Crossref match; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search35",
    "authors": [
      "Youngjun Son",
      "Ning Sun",
      "Cade Reesman",
      "David Judi",
      "Xue Li"
    ],
    "crossrefUrl": "https://doi.org/10.1016/j.ijdrr.2025.105825",
    "verifiedBy": "Melinda Muro",
    "authorAudit": "Verified",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "pdfUrl": "https://www.sciencedirect.com/science/article/pii/S2212420925006491/pdfft?isDTMRedir=true&download=true",
    "visibility": "Public"
  },
  {
    "id": "inbox-2026-10-1016-j-ecss-2025-109632",
    "inboxSourceId": "turn2search32",
    "title": "Water quality impacts during Hurricane Irene (2011) in a large coastal-plain estuary",
    "year": 2026,
    "status": "Published",
    "verification": "Verified current",
    "lead": "P. St-Laurent",
    "venue": "Estuarine, Coastal and Shelf Science",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "",
    "onlineFirst": "",
    "published": "2026-02-01",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1016/j.ecss.2025.109632",
    "url": "https://doi.org/10.1016/j.ecss.2025.109632",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search32"
    ],
    "action": "Ready for reporting; ScienceDirect PDF link may require institutional or publisher access.",
    "notes": "Source email subject: FW: ICoM webinar talk. Shared by: Hetland, Rob D. SourceRefID: turn2search32.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed; Crossref match; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search32",
    "authors": [
      "P. St-Laurent"
    ],
    "crossrefUrl": "https://doi.org/10.1016/j.ecss.2025.109632",
    "verifiedBy": "Melinda Muro",
    "authorAudit": "Verified",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "pdfUrl": "https://www.sciencedirect.com/science/article/pii/S0272771425005104/pdfft?isDTMRedir=true&download=true",
    "visibility": "Public"
  },
  {
    "id": "inbox-2026-applying-a-multisector-scenario-framework-to-evaluate-past-and-future-pu",
    "inboxSourceId": "turn2search37",
    "title": "Applying a Multisector Scenario Framework to Evaluate Past and Future Public Surface Water Supply Infrastructure Strategies in Texas",
    "year": 2026,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Perpetua I. Okoye",
    "authors": [
      "Perpetua I. Okoye",
      "Ryan A. McManamay"
    ],
    "venue": "Earth\u2019s Future",
    "type": "Journal Article",
    "topic": "Model integration",
    "due": "",
    "submitted": "",
    "accepted": "2026-04-01",
    "onlineFirst": "",
    "published": "2026-05-19",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1029/2025ef006859",
    "url": "https://doi.org/10.1029/2025ef006859",
    "pdfUrl": "https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2025EF006859",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref; MSD publication tracker workbook row 40",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search37",
      "MSD"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: new ICoM paper - scenario-based water infrastructure siting. Shared by: Sun, Ning. SourceRefID: turn2search37. Corrected lead author from inbox sharer to publisher metadata on 2026-06-09. MSD row 40 appears to correspond to this final published Earth\u2019s Future record; enriched program area on 2026-07-08.",
    "updated": "2026-07-08T12:00:00.000-07:00",
    "metadataStatus": "Crossref match; author corrected; Automated checks complete",
    "reviewFlag": "",
    "authorAudit": "Verified",
    "programAreas": "MSD",
    "sourceRecord": "turn2search37",
    "crossrefUrl": "https://doi.org/10.1029/2025ef006859",
    "verifiedBy": "Melinda Muro",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  },
  {
    "id": "inbox-2025-evaluation-of-flow-routing-james",
    "inboxSourceId": "turn2search44",
    "title": "Evaluation of Flow Routing on the Unstructured Voronoi Meshes in Earth System Modeling",
    "year": 2025,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Chang Liao",
    "venue": "Journal of Advances in Modeling Earth Systems",
    "type": "Journal Article",
    "topic": "Model integration",
    "due": "",
    "submitted": "",
    "accepted": "2025-04-08",
    "onlineFirst": "",
    "published": "2025-05-14",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1029/2024ms004737",
    "url": "https://doi.org/10.1029/2024ms004737",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search44"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: PNNL Highlight // Improving River Flow Modeling Using Unstructured Meshes in Earth System Models. Shared by: Tan, Zeli. SourceRefID: turn2search44. | Replaced email-highlight shorthand with final article title, DOI, PDF link, and author list from Crossref on 2026-06-10.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed | Crossref match; publisher DOI and PDF verified; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search44",
    "authors": [
      "Chang Liao",
      "Donghui Xu",
      "Matthew G. Cooper",
      "Tian Zhou",
      "Darren Engwirda",
      "Zeli Tan",
      "Gautam Bisht",
      "Hong-Yi Li",
      "Lingcheng Li",
      "Dongyu Feng",
      "L. Ruby Leung"
    ],
    "pdfUrl": "https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2024MS004737",
    "authorAudit": "Verified",
    "crossrefUrl": "https://doi.org/10.1029/2024ms004737",
    "verifiedBy": "Melinda Muro",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  },
  {
    "id": "inbox-2025-fast-and-accurate-simulations-of-river-flow-depth-and-velocity",
    "inboxSourceId": "turn2search45",
    "title": "An efficient hybrid downscaling framework to estimate high-resolution river hydrodynamics",
    "year": 2025,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Zeli Tan",
    "venue": "Hydrology and Earth System Sciences",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "",
    "onlineFirst": "",
    "published": "2025-08-18",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.5194/hess-29-3833-2025",
    "url": "https://doi.org/10.5194/hess-29-3833-2025",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search45"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: PNNL Highlight // Fast and Accurate Simulations of River Flow Depth and Velocity. Shared by: Leung, Lai-yung R. SourceRefID: turn2search45. | Replaced email-highlight shorthand with final HESS article title, DOI, PDF link, and author list from Crossref on 2026-06-10.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Inbox candidate; source reconciliation needed | Crossref match; publisher DOI and PDF verified; Automated checks complete",
    "reviewFlag": "",
    "programAreas": "",
    "sourceRecord": "turn2search45",
    "authors": [
      "Zeli Tan",
      "Donghui Xu",
      "Sourav Taraphdar",
      "Jiangqin Ma",
      "Gautam Bisht",
      "L. Ruby Leung"
    ],
    "pdfUrl": "https://hess.copernicus.org/articles/29/3833/2025/hess-29-3833-2025.pdf",
    "authorAudit": "Verified",
    "crossrefUrl": "https://doi.org/10.5194/hess-29-3833-2025",
    "verifiedBy": "Melinda Muro",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  },
  {
    "id": "inbox-2025-a-comparative-study-of-physics-informed-and-data-driven-machine-learning",
    "inboxSourceId": "turn2search46",
    "title": "A Comparative Study of Physics-Informed and Data-Driven Neural Networks for Compound Flood Simulation at River-Ocean Interfaces: A Case Study of Hurricane Irene",
    "year": 2025,
    "status": "Published",
    "verification": "Verified current",
    "lead": "Dongyu Feng",
    "authors": [
      "Dongyu Feng",
      "Zeli Tan",
      "Zihan Lin",
      "Donghui Xu",
      "Cheng-Wei Yu",
      "QiZhi He"
    ],
    "venue": "Journal of Geophysical Research: Machine Learning and Computation",
    "type": "Journal Article",
    "topic": "Coastal flooding",
    "due": "",
    "submitted": "",
    "accepted": "2025-09-19",
    "onlineFirst": "",
    "published": "2025-10-02",
    "indexed": "",
    "verified": "2026-06-25",
    "doi": "10.1029/2025jh000758",
    "url": "https://doi.org/10.1029/2025jh000758",
    "pdfUrl": "https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2025JH000758",
    "source": "Inbox workbook: ICoM_Publications_from_Inbox.xlsx; Crossref",
    "tags": [
      "Inbox",
      "Email intake",
      "turn2search46"
    ],
    "action": "Ready for reporting; recheck DOI and PDF links before the next formal submission.",
    "notes": "Source email subject: FW: PNNL Highlight // Machine Learning Improves Compound Flood Simulation in Earth System Models. Shared by: Tan, Zeli. SourceRefID: turn2search46. Corrected DOI, full title, journal, dates, and author list from Crossref and OSTI metadata on 2026-06-10.",
    "updated": "2026-06-25T12:00:00.000-07:00",
    "metadataStatus": "Crossref match; OSTI match; author corrected; Automated checks complete",
    "reviewFlag": "",
    "authorAudit": "Verified",
    "ostiId": "2997685",
    "ostiUrl": "https://www.osti.gov/biblio/2997685",
    "doePagesUrl": "https://www.osti.gov/pages/biblio/2997685",
    "programAreas": "",
    "sourceRecord": "turn2search46",
    "crossrefUrl": "https://doi.org/10.1029/2025jh000758",
    "verifiedBy": "Melinda Muro",
    "linkStatus": "Links checked: DOI verified by Crossref; Publisher/DOI link present; Publisher PDF link present; OSTI/DOE PAGES link present",
    "linkChecked": "2026-06-25",
    "visibility": "Public"
  }
];
